(setq mark-holidays-in-calendar t)
(setq christian-holidays nil)
(setq hebrew-holidays nil)
(setq hebrew-holidays-1 nil)
(setq hebrew-holidays-2 nil)
(setq hebrew-holidays-3 nil)
(setq hebrew-holidays-4 nil)
(setq islamic-holidays nil)
(setq bahai-holidays nil)

(when (package-installed-p 'cal-china-x)
  (require 'cal-china-x)
  (setq calendar-chinese-all-holidays-flag t))

(provide 'holiday-config)
