* README
** About the "Emacs" repository
This repo is an emacs configurations collection.
*** How to install
You can clone the repo to some directory you like:
#+BEGIN_SRC bash
cd ~/<directory-you-like>
git clone https://github.com/gadmyth/emacs.git
#+END_SRC

Now you should config the .emacs file. You can make a symbolic link to the .emacs in the emacs.git repo, or you create a .emacs file, and write elisp script to load the .emacs in the emacs.git:
#+BEGIN_SRC bash
# way one: make a symbolic link
cd ${HOME}
ln -sf ~/<directory-you-like>/emacs/init-scripts/.emacs

# way two: write loading script into a new ~/.emacs
cd ${HOME}
rm -rf .emacs
cat >> .emacs << EOF
(load-file (expand-file-name "~/<directory-you-like>/emacs/init-scripts/.emacs"))
EOF
#+END_SRC

** Loading Order
*** directories
There're four main directories in this repo, init-scripts, el-pre-scripts, basic-scripts, el-extends, el-post-scripts.

The init-scripts directory include 4 init scripts. .emacs define the \+emacs-context-directory\+ equals to "~/<parent dir>/emacs/", and load the emacs.init.el file, this init file load the .emacs.frame.el under non-terminal environment.
*** .emacs.frame.el
This is the main config file under GUI environment. It put the basic-scripts, el-pre-scripts, el-extends, el-post-scripts first into the load-path.

The script-extends package define the functions to load all files under the certain directory. The loading order is first load all elisp files under el-pre-scripts dir, and then require the \+required-packages\+ defined in the packages.el. These packages are all original packages can be downloaded from package-archives sources. 

Then load the config packages under basic-scripts dir optionally. Then load the must files, the must files should be defined in the elisp scripts under the el-pre-scripts dir.

Then load all the extend elisp scripts under the el-extends dir, load all the script files under the el-post-scripts dir.
